### ISSUE TITLE
Description: Unresolved reference: com.anylogic.rl.libraries.bonsai. Location: Activity Based Costing Analysis (Bonsai) - Model

### ISSUE THREAD

**Issue by KevinChngJY** [BonsaiAI/bonsai-anylogic#14]
After importing into Anylogic, I have error below:
Description: Unresolved reference: com.anylogic.rl.libraries.bonsai. Location: Activity Based Costing Analysis (Bonsai) - Model

**Comment by ThomasGVoss** [comment]
I got the same error - looks like we are missing the offline library (*.jar).
I found this: https://www.anylogic.de/blog/train-ai-agents-with-microsoft-project-bonsai/ 
you can get the needed files as well as documentation there.  It is also available in this [folder](https://github.com/microsoft/bonsai-anylogic/tree/master/connector) within the repo.
Since the post is about 4 months old, not sure if that still applies tho. Might also be related to #9 ?

**Comment by t-wolfeadam** [comment]
@KevinChngJY - Thomas is correct in what's wrong. Though fyi the files at the blog are severely outdated and the PR is just cleaning up the ABCA example.

To fix the error, download the jar and the accompanying lib directory from the "connector" folder in this repo (unfortunately, you may need to download the whole project) - put both in a location where they won't be moved/deleted. Then, follow [these instructions](https://anylogic.help/advanced/libraries/managing-libraries.html) to add it to your AnyLogic palette.

**Comment by KevinChngJY** [comment]
Thanks All, it resolved the error.
